name: Kotlin CI/CD

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Build
        env:
          ORG_GRADLE_PROJECT_NEXUSUSERNAME: "${{ secrets.nexusUsername }}"
          ORG_GRADLE_PROJECT_NEXUSPASSWORD: "${{ secrets.nexusPassword }}"
          ORG_GRADLE_PROJECT_SIGNINGKEYID: "${{ secrets.signingKeyId }}"
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: "${{ secrets.signingPassword }}"
        run: ./gradlew clean && ./gradlew build

      - name: Test
        env:
          ORG_GRADLE_PROJECT_NEXUSUSERNAME: "${{ secrets.nexusUsername }}"
          ORG_GRADLE_PROJECT_NEXUSPASSWORD: "${{ secrets.nexusPassword }}"
          ORG_GRADLE_PROJECT_SIGNINGKEYID: "${{ secrets.signingKeyId }}"
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: "${{ secrets.signingPassword }}"
        run: ./gradlew test

  publish:
    name: Publish to Maven Central
    if: contains(github.ref, 'release/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Install GPG key
        run: |
          cat <(echo -e "${{ secrets.signingKey }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Install gpg2
        run: sudo apt-get install gnupg2 -y

      - name: Publish artifact
        env:
          ORG_GRADLE_PROJECT_NEXUSUSERNAME: "${{ secrets.nexusUsername }}"
          ORG_GRADLE_PROJECT_NEXUSPASSWORD: "${{ secrets.nexusPassword }}"
          ORG_GRADLE_PROJECT_SIGNINGKEYID: "${{ secrets.signingKeyId }}"
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: "${{ secrets.signingPassword }}"
          GPG_TTY: $(tty)
        run: ./gradlew publish
